### ISSUE TITLE
Multiplication is not dividing in the RMS norm.

### ISSUE THREAD

**Issue by srikant86panda** [hkproj/pytorch-llama#2]
I appreciate you producing such intriguing and valuable articles. an excellent learning resource.

Just wanted to confirm: At present, we have multiplication and not divide in the RMS norm.

Current:
x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)

Is this true:
x / torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)

**Comment by hkproj** [comment]
Hi, the function used is `rsqrt`, which is equivalent to `1 / sqrt`. This is why we are multiplying.

**Comment by srikant86panda** [comment]
yes, you are right. I missed..
