### ISSUE TITLE
Where did the factor 2 go in rotary embedding?

### ISSUE THREAD

**Issue by ZhichaoDuan** [hkproj/pytorch-llama#3]
Well, thanks for you great video on youtube. I just got one question, in your implementation, in method precompute_theta_pos_frequencies. The equation of theta contains a factor 2 like you wrote in your comment, theta_i = 10000^(-2(i-1)/dim) for i = [1, 2, ... dim/2]. However, in your code, I don't see a factor 2 added, how is that?

**Comment by OmPrasad93** [comment]
@ZhichaoDuan 
theta_numerator = torch.arange(0, head_dim, 2).float()

This line creates a tensor starting at 0 and stepping by 2. If head_dim is 6, for instance, theta_numerator would be [0, 2, 4]. These values correspond to 2(i-1) where i starts from 1. In other words, for i = 1, 2, 3, ..., theta_numerator directly represents 2(i-1).

**Comment by hkproj** [comment]
Thank you @OmPrasad93, that's correct.
