### ISSUE TITLE
alternative implementation of group-query attention (GQA)

### ISSUE THREAD

**Issue by feixyz10** [hkproj/pytorch-llama#8]
here is a probably-better [implementation](https://github.com/feixyz10/pytorch-llm-infer/blob/main/model/attention.py#L6) for [group-query attention](https://github.com/hkproj/pytorch-llama/blob/067f8a37fe36ac8b52dca9cc6f2a2e8d6aa372d6/model.py#L159) which might run faster. It utilize a property of pytorch that matmul is broadcasting.

**Comment by hkproj** [comment]
To be honest, the [implementation you're referring to](https://github.com/feixyz10/pytorch-llm-infer/blob/13dac0f662eff996bfd25c28c210611a48d75ee8/model/attention.py#L97-L98) still replicates the missing heads - which is also what I do using the repeat_kv method - so the overall computation is the same as the "normal attention" with all the heads for Q, K and V. Only way to compute it efficiently is to use a custom CUDA kernel.

**Comment by feixyz10** [comment]
In my opinion, since broadcasting matrix multiplication in pytorch is efficient enough (pure c++ or CUDA implementaion under the hook), replication of the missing heads is not needed.

**Comment by hkproj** [comment]
Yes, but broadcasting only works in the case of MQA. Does not work for GQA. Or am I missing something?

**Comment by feixyz10** [comment]
Assume nheads=6, nkvheads=2. we can reshape so that Q with shape 2x3, then transpose to 3x2; and reshape K/V with shape 1x2. Now doing matmul (transpose back is needed) we will be equivalent to doing repeat-and-matmul.

**Comment by hkproj** [comment]
Interesting approach - thanks for sharing! I'll play with it in the weekend
